org: groros
app: pay-per-lead-project
service: create-new-roofing-contractor-webhook
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  iam:
    role:
      statements:
      - Effect: Allow
        Action: states:StartExecution
        # will need to be changed for each service
        Resource: arn:aws:states:us-east-1:906360379090:stateMachine:Create-New-Roofer
  environment:
    STATE_MACHINE_ARN: arn:aws:states:us-east-1:906360379090:stateMachine:Create-New-Roofer
functions:
  hello:
    handler: handler.create_new_roofer_webhook
    events:
      - httpApi:
          path: /
          method: post 


plugins:
  - serverless-wsgi
  - serverless-python-requirements
